[tool.poetry]
name = "python-machina-academy"
version = "0.1.0"
description = ""
authors = ["Tomislav Nazifović <tomislav.nazifovic@gmail.com>"]
readme = "README.md"
packages = [{include = "python_machina_academy"}]

[tool.poetry.dependencies]
python = "3.11.9"
ipykernel = "^6.29.5"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
